### ISSUE TITLE
My GPU on my Mac overheats when running Overlap2D

### ISSUE THREAD

**Issue by KevinNorth** [UnderwaterApps/overlap2d#413]
When I run Overlap2D on my Mac, my GPU quickly reaches nearly 100ºC and stays at that temperature until I close the editor. This happens even when I leave Overlap2D running in the background without opening a project.

Here's a screenshot showing the temperature of my GPU when I'm running Overlap2D:

<img id="__wp-temp-img-id" src="https://dl.dropboxusercontent.com/u/35569278/computer_temperature_screenshot_for_overlap2D.png" width="398" height="456" />

Notice my fan speeds and the "TXGX PECI GPU" temperature. The CPU is doing fine.

Here are my computer's specs:

General information:
<ul>
 	<li>Model Name: MacBook Pro</li>
 	<li>Model Identifier: MacBookPro11,2  Processor Name: Intel Core i7</li>
 	<li>Processor Speed: 2.2 GHz</li>
<li>  Number of Processors: 1</li>
<li>Total Number of Cores: 4</li>
<li>  Memory: 16 GB</li>
<li>  Boot ROM Version: MBP112.0138.B17</li>
</ul>

GPU:

<ul>
<li>Chipset Model: Intel Iris Pro</li>
<li>Type: GPU</li>
<li>Bus: Built-In</li>
<li>VRAM (Dynamic, Max): 1536 MB</li>
<li>Vendor: Intel (0x8086)</li>
</ul>

Molitor:

<ul>
<li>Display Type: Retina LCD</li>
<li>Resolution: 2880 x 1800 Retina</li>
<li>Pixel Depth: 32-Bit Color (ARGB8888)</li>
</ul>

My computer is running Java 1.8.0_74 as its JRE.

I also posted this issue on the [Overlap2D community forums](http://overlap2d.com/forums/topic/my-gpu-on-my-mac-overheats-when-running-overlap2d/).

**Comment by KevinNorth** [comment]
(I also posted this issue on the [Overlap2D community forums](http://overlap2d.com/forums/topic/my-gpu-on-my-mac-overheats-when-running-overlap2d/).)

**Comment by bruceloco** [comment]
I'm still new at this, I have not see the graphical calls, but it could be a java issue.
How do other java apps behave? play some sort of graphics intensive java game and see if it has anything to do with your java version

**Comment by meonlineonmess** [comment]
I am also experiencing high CPU usage with Overlap2D and also VisEditor when these 2 and minimized on OS X. Please fix the issue on Overlap2D.

**Comment by bruceloco** [comment]
VisEditor is also based on Java.
What is your graphics card?
Sounds like it could be java trying to us hardware acceleration via OpenCL and doing it wrongly.

**Comment by meonlineonmess** [comment]
I have a mac retina early 2015 which has intel iris graphics 6100. I am 100% the issue is only on macOS because I just tried 5 minutes ago Overlap2D in a Windows 7 virtual machine and I get no issue in Windows, just on OS X. I use AppPolice to limit the cpu usage of the Overlap2D process which I keep it at 20%. Therefor I do not permit it to go higher than that, but it is using resources for no reason and I read on this forum that it has something to do with the FPS which tries to go over 60 fps. The thing is that in OS X Mavericks and macOS Sierra all apps are limited to 60fps and they can not go higher, whereas in older OS X versions this limitation was not imposed. I used an app to see how many FPS I get when running Overlap and it always shows me 60fps and sometimes 61.5 and it looks like something is struggling to keep the FPS below 60. In other apps when running them I get around 10 fps when moving the mouse.

It is definetly something with the rendering, unfortunately I have no idea how to fix it. I read here that it was fixed in some early release but it doesn't seem to the case and I am not the only one experiencing this issue.

I hope my information will help fix this issue somehow, because Overlap2D is awesome :)

**Comment by bruceloco** [comment]
Can you build from source?
I think I might have found the place to fix this

**Comment by meonlineonmess** [comment]
Well I just downloaded the sources and I imported the gradle projects in my eclipse workspace(common-api,master,runtime-libgdx, extension and spine-runtime-libgdx). The master project and the spine-runtime-libgdx both are marked as having issues because of some missing imports. If you'll tell me where to change the code to make it work I'll give it a try to see if it'll fix the problem and I will let you know :).

**Comment by bruceloco** [comment]
I am not even sure it is this file, I was just looking a bit on how this is done and trying to find bugs on the underlying libs:
this led me to package com.badlogic.gdx.backends.lwjgl, function LwjglApplicationConfiguration:

	public boolean vSyncEnabled = true;
and
	/** Target framerate when the window is in the foreground. The CPU sleeps as needed. Use 0 to never sleep. **/
	public int foregroundFPS = 60;
	/** Target framerate when the window is not in the foreground. The CPU sleeps as needed. Use 0 to never sleep, -1 to not render. **/
	public int backgroundFPS = 60;

based on these threads:
https://github.com/libgdx/libgdx/issues/3629
I could be totally off track but give it a go

**Comment by bruceloco** [comment]
Ah yeah, there were some instructions on the forum on how to build from source:
http://overlap2d.com/forums/topic/how-to-compile-and-run-overlap2d-editor-from-source-code/
Otherwise you can't build it

**Comment by meonlineonmess** [comment]
I get too many errors(100) after running  ./gradlew assemble

**Comment by meonlineonmess** [comment]
I downloaded the source files and after importing the repo in eclipse it can not find the main class to run. In Run Configurations I can't select it. I guess I am supposed to run ./gradlew assemble first and after that it'll generate some other files. I don't know.

**Comment by bruceloco** [comment]
use git and follow the advice on the forum to set the branch

**Comment by meonlineonmess** [comment]
I get this error when compiling:

"IdeaProjects/overlap2d/spine-runtimes/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/Animation.java:770: error: cannot find symbol
                        float[] vertices = verticesArray.setSize(vertexCount);
                                                        ^
  symbol:   method setSize(int)
  location: variable verticesArray of type FloatArray

"

**Comment by bruceloco** [comment]
2
3
4
5
6
7
8
9
git clone https://github.com/UnderwaterApps/overlap2d.git
cd overlap2d
./gradlew assemble
cd spine-runtimes
git checkout 419982695f3e41e36e7582ccf26c85db897c0416
cd ..
./gradlew build
./gradlew run

for me the error went away

**Comment by meonlineonmess** [comment]
well I got my clone using git from IntelliJ this time and at "./gradlew assemble" I get the failed message cause of some methods like setSize() which could not be found

**Comment by bruceloco** [comment]
yeah, I don't use intelij to build anymore, just command line

**Comment by meonlineonmess** [comment]
this time I used the terminal to clone the repo and I got the same error :|

**Comment by bruceloco** [comment]
did you just run the commands as pasted? or did you use intelij to build?
the above commands worked for me. I have jdk 8, java runtime 1.8, gradle 3.3
Running a 2009 27" imac with Sierra on it

**Comment by meonlineonmess** [comment]
I recorded my terminal actions. You can watch the video clip here, it is a dropbox share link->. https://www.dropbox.com/s/3iuf47bt7rlmimm/Issue.mov?dl=0.

**Comment by bruceloco** [comment]
./gradlew assemble is expected to fail.

Go ahead and do this after it fails:
cd spine-runtimes
git checkout 419982695f3e41e36e7582ccf26c85db897c0416
cd ..
./gradlew build
./gradlew run

**Comment by meonlineonmess** [comment]
ok it opens Overlap after building and ./gradlew run.

**Comment by bruceloco** [comment]
now you can play with the settings above:

public boolean vSyncEnabled = true; <- possibly try with false
and
/** Target framerate when the window is in the foreground. The CPU sleeps as needed. Use 0 to never sleep. /
public int foregroundFPS = 60;
/ Target framerate when the window is not in the foreground. The CPU sleeps as needed. Use 0 to never sleep, -1 to not render. **/
public int backgroundFPS = 60; <- possibly -1, not sure why this would actually be enabled for background work

**Comment by meonlineonmess** [comment]
ok I'll try at 12 o'clock cause I have to go to sleep. It is 3:30am where I live. I guess I have to replace the  .jar dependency with the modified one(new jar compilation from https://github.com/libgdx/libgdx/tree/master/backends/gdx-backend-jglfw/src/com/badlogic/gdx/backends/jglfw ), right? cause the .class can not be changed.

**Comment by meonlineonmess** [comment]
I can't change the vSync variable because it is in a .class file and it is a Gradle dependency which I guess it means that it always downloads the requested .jar and it overwrites it.

**Comment by bruceloco** [comment]
I'm trying to decompile the file
gdx-backend-lwjgl-1.7.1.jar(stored in the gradle cache) to edit it to change the settings and see if this is the issue.
Then you can edit build.gradle and comment out:
    compile "com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion"

However, I have never done java before or intelij or whatever so it is a bit of a hard effort for me.

**Comment by meonlineonmess** [comment]
I tried to integrate a Scene into my project but the tutorials are beyond outdated

**Comment by azakhary** [comment]
Hi guys! can I help in any way? what has to be changed to fix this? I am not sure why you try to decompile things, if the source is already here to change things in it?

**Comment by meonlineonmess** [comment]
@azakhary  you could try to play with the vSync feature to turn it off just to see if makes a difference on macOS.

public boolean vSyncEnabled = true; <- possibly try with false
and
/** Target framerate when the window is in the foreground. The CPU sleeps as needed. Use 0 to never sleep. /
public int foregroundFPS = 60;
/ Target framerate when the window is not in the foreground. The CPU sleeps as needed. Use 0 to never sleep, -1 to not render. **/
public int backgroundFPS = 60; <- possibly -1, not sure why this would actually be enabled for background work

**Comment by azakhary** [comment]
I do remember that it is related, and I tried something like that but it broke something else, while fixed the CPU load. I'll try from osx machine when I get to office. But if you guys can just run it from sources, then take a look at Main.java ( https://github.com/UnderwaterApps/overlap2d/blob/master/overlap2d/src/com/uwsoft/editor/Main.java#L69) maybe you can configure vSync for JglfwApplication or config (one of them has to have that)

**Comment by bruceloco** [comment]
@meonlineonmess did you manage to decompile/change settings/recompile?
I read that there are lots of issues with libdgx on osx with intel iris chips.

**Comment by azakhary** [comment]
I think vsync can be set in JglfwApplicationConfiguration config in Main.java that's the easiest way to test it.

**Comment by bruceloco** [comment]
@azakhary ah, that way is way easier
I will give it a go

**Comment by meonlineonmess** [comment]
@azakhary should it be like a vm args thing? like -vsync=false ?

**Comment by azakhary** [comment]
Thanks! Let us know if it helps. to my knowledge, it should help, but will break something else, that is probably easy or hard to fix. Anyway, I am curious too.

**Comment by azakhary** [comment]
@meonlineonmess  all you need to do is to add this line in Main.java 
after:
JglfwApplicationConfiguration config = new JglfwApplicationConfiguration();
...
config. setVSync(false);

**Comment by meonlineonmess** [comment]
ok I'll give it a try

**Comment by azakhary** [comment]
And this will only be for osx, as it is in OSX if block.

**Comment by meonlineonmess** [comment]
Ok I compiled it and this is where I changed the code:

config.vSync=false;--> with this option off when Overlap2D is opened the CPU usage stays around 50% but does not go further and the FPS counter shows me 252 fps. The good thing is that when the app is minimized the cpu usage goes to sleep whereas before it kept on running.


"
if (SystemUtils.IS_OS_MAC_OSX || SystemUtils.IS_OS_MAC) {
            System.setProperty("apple.laf.useScreenMenuBar", "true");
            System.setProperty("com.apple.mrj.application.apple.menu.about.name", "Overlap2D");
            JglfwApplicationConfiguration config = new JglfwApplicationConfiguration();
            config.width = (int) (width);
            config.height = (int) (height - height * .04);
            config.backgroundFPS = 0;
	    config.vSync=false;  < ---
            config.title = "Overlap2D - v" + AppConfig.getInstance().version;
            new JglfwApplication(overlap2D, config);
        } else {

"

**Comment by bruceloco** [comment]
so as far as your machine is concerned it is fixed with the vsync right?

**Comment by meonlineonmess** [comment]
@bruceloco  no it is not fixed because when Overlap2D is in focus the CPU still gets hot over 80 Degrees. With config.vSync=false; I can turn the CPU usage off by minimizing the program whereas before it kept running even when it was minimized.

**Comment by bruceloco** [comment]
how about reducing foregroundFPS?
by default it is set to 60

**Comment by meonlineonmess** [comment]
Why does it use unnecessary fps? 250 or 60 is way to high for this application

**Comment by meonlineonmess** [comment]
ok example when using the mail program I get around 15 fps and when scrolling through the messages using the touchpad with innertia it goes as far as ~30 fps. However in Overlap2D it needs more than 252 fps with an empty scene.

**Comment by azakhary** [comment]
adding config.setForegroundFPS(60) ; should fix the issue, I suppose.

**Comment by bruceloco** [comment]
this is more likely a jglfw problem, the opengl java framework.
I have not really done anything with the program yet, just fixed the weird button alignment issue so I have not see any performance impact
or 
config.foregroundFPS = 60;

**Comment by bruceloco** [comment]
Ah, in the libray, this is not set by default to anything...
that is why it must be trying to max out
on jglfw there is nothing on the defaults and this one is used on OSX, only on Lwjgl which is used on the windows build

**Comment by azakhary** [comment]
yep. sounds reasonable. so setting it from code in config, should be required then.

**Comment by meonlineonmess** [comment]
I tried config.foregroundFPS=60 but it does not fix the issue

**Comment by azakhary** [comment]
they also have some kind of hiddenFPS param. I have no idea what it does though.

**Comment by meonlineonmess** [comment]
i'll try it

**Comment by bruceloco** [comment]
/** Target framerate when the window is in the foreground. The CPU sleeps as needed. Use 0 to never sleep. **/
	public int foregroundFPS;
	/** Target framerate when the window is in the background. The CPU sleeps as needed. Use 0 to never sleep, -1 to not render. **/
	public int backgroundFPS;
	/** Target framerate when the window is hidden or minimized. The CPU sleeps as needed. Use 0 to never sleep, -1 to not render. **/
	public int hiddenFPS = -1;

**Comment by azakhary** [comment]
so background and hidden has to be -1, and foreground 60.. i guess.

**Comment by meonlineonmess** [comment]
IT WORKS!!!

These are the settings that worked :

    "       config.backgroundFPS = -1;
	    config.foregroundFPS = 60;
	    config.hiddenFPS = -1;
	    config.vSync = false;"

No more 80 Degrees on the CPU!!!
The FPS counter stays low at about 3 FPS when idle and also when not in focus !!!

**Comment by meonlineonmess** [comment]
CPU usage is also very low at about 0,2 when idle+ in focus or not in focus.

**Comment by meonlineonmess** [comment]
Overlap2D now seems to be also way much smoother and stable when working with it.

**Comment by azakhary** [comment]
can you do a pull request? I'll merge it right away!

**Comment by meonlineonmess** [comment]
I'll try

**Comment by bruceloco** [comment]
I get a blank screen with backgroundFPS = -1

**Comment by meonlineonmess** [comment]
I can't do a pull request and I tried to commit the change for review but it asks me for a username and password. I guess I do not have permissions.

this is the change I did in the Main class method startLoadingEditor():

"
if (SystemUtils.IS_OS_MAC_OSX || SystemUtils.IS_OS_MAC) {
            System.setProperty("apple.laf.useScreenMenuBar", "true");
            System.setProperty("com.apple.mrj.application.apple.menu.about.name", "Overlap2D");
            JglfwApplicationConfiguration config = new JglfwApplicationConfiguration();
            config.width = (int) (width);
            config.height = (int) (height - height * .04);
            config.backgroundFPS = -1;
	    config.foregroundFPS = 60;
	    config.hiddenFPS = -1;
	    config.vSync = false;
            config.title = "Overlap2D - v" + AppConfig.getInstance().version;
            new JglfwApplication(overlap2D, config);
        } 
"

@bruceloco I do not get black screen.

**Comment by bruceloco** [comment]
@meonlineonmess do you do ./gradlew run to run?

**Comment by azakhary** [comment]
well, no problem, I can do the change myself. But given it doesnot work for @bruceloco  I guess this needs to be figured out first.

**Comment by meonlineonmess** [comment]
@bruceloco yes I do

**Comment by meonlineonmess** [comment]
./gradlew build   then
./gradlew run

**Comment by meonlineonmess** [comment]
@azakhary @bruceloco  do you know some updated tutorials or updated documentation for loading Overlap2D in libGDX? the code for Overlap2D is outdated.

**Comment by bruceloco** [comment]
Ok, so, this is somewhat interesting.
I know why it does not redraw.
So I have the same settings as you
run the same commands
however I get a black screen
if I tab off to another app and tab again, now the menu appears.
It is like it starts in the background and does not respond to anything because it assumes it is in the foreground
then switch to another window and back and it now assumes foreground position and it starts working.

**Comment by azakhary** [comment]
@bruceloco  I am curious if we can somehow "fake" that going back and forth to make it think it's in foreground on start. Maybe it's possible to stackoverflow that.

@meonlineonmess the docs on website should be latest:
http://overlap2d.com/runtimes-documentation/
Scroll down to the tutorials section, and watch first video.

**Comment by azakhary** [comment]
@meonlineonmess  also check out the runtimes wiki: https://github.com/UnderwaterApps/overlap2d-runtime-libgdx/wiki

**Comment by bruceloco** [comment]
@azakhary where is the overlap2 jar actually built?
I can try to run this directly to make sure it is not an issue with my jdk/jvm
There is a thread here:
https://hub.jmonkeyengine.org/t/glfw-crash-on-macs/34719/16
where it basically says that threads are competing and in my case the java thread takes precedence and sends the jglfw thread into background

**Comment by meonlineonmess** [comment]
My .jar shows up here ->/Users/ublack/overlap2d/build/libs/overlap2d-0.1.3.jar however I can't run it and I don't know if it is the right jar for sure.

**Comment by azakhary** [comment]
to build a jar, you need to run "dist" gradle task.

**Comment by meonlineonmess** [comment]
I built mine using ./gradlew dist and when I start the program I also get black screen for a couple of seconds and then it opens.

**Comment by bruceloco** [comment]
same thing on the built jar, must be some sort of setting 
@meonlineonmess what's your jvm/jdk versions?

**Comment by meonlineonmess** [comment]
aBlacks-MacBook-Pro:~ ublack$ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
aBlacks-MacBook-Pro:~ ublack$

**Comment by azakhary** [comment]
btw, if we put value 60, on all hidden, background and foreground, wouldn't it be still awesome CPU for all cases with no possible no-render bug? (as a compromise solution)

**Comment by meonlineonmess** [comment]
@azakhary I'll try

**Comment by meonlineonmess** [comment]
with 60,60,60 it still doesn't get hot but my FPS counter now shows it is using 68 fps to render the program. The process of Overlap doesn't go below 9% which means it is using resources that it should now use. It drains the battery faster.

**Comment by bruceloco** [comment]
I got 
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
wonder if that is the problem

**Comment by bruceloco** [comment]
@meonlineonmess 
can you try my jar?
https://www.dropbox.com/sh/9dza1t1alaxc98x/AAADmV03TMLjYxmOezu5fxNSa?dl=0

**Comment by meonlineonmess** [comment]
@bruceloco  I  opened your jar and I get the same behaviour as before: black screen when opening and then after a couple of seconds it shows the content. I also get low fps and low cpu usage whether if the program is minimized, in or not in focus.

**Comment by meonlineonmess** [comment]
It seems to work ok despite the black screen at which one is supposed to wait a little.

**Comment by bruceloco** [comment]
i have it opened for a minute and nothing

**Comment by meonlineonmess** [comment]
@bruceloco I switched between programs and only after that it showed up the content.

**Comment by bruceloco** [comment]
whats your jdk?
so it's not the player and not the source code, so we are up to the compiler now

**Comment by azakhary** [comment]
Maybe it's the you run it? double clicking, versus right click open or some other way, may make it go to background during the startup sequence, and silently come back, leaving jglfw think that it's still on background. imho it's either osx version difference, or just the way the app is executed.

**Comment by bruceloco** [comment]
@azakhary @meonlineonmess has the same behaviour as me running on his system with the app I built.
I got OSX Sierra, 64bit. I am assuming that his is the same.
So I am inclined towards the JDK version.
I installed gradle via sdkman, I am using Gradle 3.3
My jdk is 1.8.0_112

**Comment by bruceloco** [comment]
Ok,
if I do:
            System.setProperty("apple.laf.useScreenMenuBar", "true");
            System.setProperty("com.apple.mrj.application.apple.menu.about.name", "Overlap2D");
            LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
            config.width = (int) (width);
            config.height = (int) (height);
            config.backgroundFPS =-1;
            config.foregroundFPS = 60;
            config.vSyncEnabled = false;
            config.title = "Overlap2D - v" + AppConfig.getInstance().version;
            new LwjglApplication(overlap2D, config);

for OSX it works, stays a couple seconds black but works
But the switching of libraries here, using the LWJGL vs the JGLFW, not sure about the impact here

**Comment by meonlineonmess** [comment]
I use macOS Sierra 10.12.2 and Oracle JDK 

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

**Comment by meonlineonmess** [comment]
I wonder if VisEditor suffers from the same issue with the black screen. It also has the high CPU usage too and I saw the source code and it's the same issue there too with LwglApplication...  Maybe after adding the settings for VisEditor like in Overlap2D, it will suffer from the same issue with the black screen.

**Comment by bruceloco** [comment]
also, I was just reviewing badlogic's repos and the lwjgl vs jglfw, and the jglfw repo has not been updated in 3 years.
also the badlogic libs for both lwjgl and jglfw are also at least 2 years old and all the new stuff comes on lwjgl3.
@azakhary any reason why the repo did not move?

**Comment by bruceloco** [comment]
@meonlineonmess lets keep the issue here based on overlap2D.

**Comment by bruceloco** [comment]
Also for future reference:
VSync is enabled by default on OSX and cannot be disabled easily
Someone created the following tool:
https://www.tonymacx86.com/threads/beamsyncdropper-tool-to-disable-beamsync-permanently.92201/

**Comment by meonlineonmess** [comment]
@bruceloco As far as I remember BeamSyncDropper when I used this app it did not work in El Capitan or Sierra because the rendering was changed in these versions.

**Comment by bruceloco** [comment]
@meonlineonmess yeah, don't see any updates on the project for 2 years.

**Comment by bruceloco** [comment]
@meonlineonmess have you tried using lwjgl on mac?
Since I don't have any project running I cannot see any issues/performance impact

**Comment by meonlineonmess** [comment]
@bruceloco  no I didn't use it before

**Comment by bruceloco** [comment]
can you try with these settings?
System.setProperty("apple.laf.useScreenMenuBar", "true");
System.setProperty("com.apple.mrj.application.apple.menu.about.name", "Overlap2D");
LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
config.width = (int) (width);
config.height = (int) (height);
config.backgroundFPS =-1;
config.foregroundFPS = 60;
config.vSyncEnabled = false;
config.title = "Overlap2D - v" + AppConfig.getInstance().version;
new LwjglApplication(overlap2D, config);

Thanks

**Comment by azakhary** [comment]
there was a reason we used Jglfw instead of Lwjgl. if you change it, other things will not work.

**Comment by bruceloco** [comment]
@azakhary does this include lwjgl3? or the standard lwjgl? you use it on windows, so there might be a mac bug or two which could easily be addressed no?

**Comment by azakhary** [comment]
standart lwjgl. so yeah, 3 might be good. dunno

**Comment by meonlineonmess** [comment]
Will Overlap2D ever support Box2D Joints? and when will it get out of the Alpha version?

**Comment by azakhary** [comment]
Sadly I am afraid, I am occupied currently with other projects. So can't say anything.

**Comment by meonlineonmess** [comment]
Adding Box2D joints and keeping it free will surely increase the programs popularity which means Ads can generate revenue. Just keep in mind the fact that to develop a game requires some time and this means Overlap2D will be kept opened generating revenue through Ads Impressions.

**Comment by bruceloco** [comment]
@meonlineonmess add the feature on the program.
Or lets discuss this on the forum. This section is for ticket management
